version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    image: ellen25/backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    image: ellen25/frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
